/**
 * Popup.
 *
 * Loads the shared libraries via script tags rather than the concatenated
 * bundle, so the settings schema here is literally the same code the engine
 * uses. Nothing in this file re-derives a default.
 */
(function () {
  'use strict';

  const api = globalThis.browser && globalThis.browser.runtime ? globalThis.browser : globalThis.chrome;
  const NX = globalThis.NX;
  const { MSG } = NX.browser;

  const el = (id) => document.getElementById(id);
  const state = { settings: null, origin: null, tabId: null };

  const MODES = [
    ['auto', 'Automatic', 'Measures the page and picks the best method.'],
    ['native', 'Site theme only', "Only uses the site's own dark theme. Never recolours."],
    ['dynamic', 'Generated', 'Always builds a theme from the page colours.'],
    ['filter', 'Invert', 'Flips every colour. Works anywhere, looks roughest.'],
  ];

  /** Human wording for what the engine actually did. */
  const TIER_COPY = {
    0: ['off', 'Not themed on this page'],
    1: ['native', "Using this site's own dark theme"],
    2: ['generated', "Recoloured from this site's design tokens"],
    3: ['generated', 'Generated theme from the page colours'],
    4: ['filter', 'Inverted, because nothing cheaper worked'],
  };

  function renderPalettes() {
    const host = el('palettes');
    host.textContent = '';
    for (const [id, palette] of Object.entries(NX.theme.PALETTES)) {
      const button = document.createElement('button');
      button.type = 'button';
      button.className = 'swatch';
      button.setAttribute('role', 'radio');
      button.setAttribute('aria-checked', String(state.settings.palette === id));
      button.title = palette.label;

      const chip = document.createElement('span');
      chip.className = 'chip';
      // The swatch is generated by the real transform, so what you see is
      // exactly what the palette does to a white page and its text.
      const bg = NX.color.format(NX.theme.mapBackground([1, 1, 1], { palette: id }));
      const fg = NX.color.format(NX.theme.mapForeground([0, 0, 0], { palette: id }));
      chip.style.background = `linear-gradient(135deg, ${bg} 0 62%, ${fg} 62% 100%)`;

      const name = document.createElement('span');
      name.className = 'name';
      name.textContent = palette.short || palette.label;

      button.append(chip, name);
      button.addEventListener('click', () => save({ palette: id }));
      host.append(button);
    }
  }

  function renderModes() {
    const host = el('modes');
    host.textContent = '';
    const current = siteValue('mode');
    for (const [id, label, hint] of MODES) {
      const button = document.createElement('button');
      button.type = 'button';
      button.className = 'mode';
      button.setAttribute('role', 'radio');
      button.setAttribute('aria-checked', String(current === id));
      button.textContent = label;
      button.title = hint;
      button.addEventListener('click', () => saveSite({ mode: id }));
      host.append(button);
    }
    const active = MODES.find(([id]) => id === current);
    el('mode-hint').textContent = active ? active[2] : MODES[0][2];
  }

  /** The effective value for this site: the override if there is one. */
  function siteValue(key) {
    const site = (state.settings.sites || {})[state.origin] || {};
    return site[key] !== undefined ? site[key] : state.settings[key];
  }

  function renderSliders() {
    for (const key of ['brightness', 'contrast', 'saturation']) {
      const input = el(key);
      const value = siteValue(key);
      input.value = value;
      el(`${key}-out`).textContent = value;
    }
  }

  function render() {
    const settings = state.settings;
    document.body.dataset.enabled = String(settings.enabled);
    el('global').checked = settings.enabled;

    el('site-name').textContent = state.origin || 'this page';
    const site = (settings.sites || {})[state.origin] || {};
    el('site').checked = site.enabled !== false;
    el('site').disabled = !state.origin;

    renderPalettes();
    renderSliders();
    renderModes();
    refreshStatus();
  }

  async function refreshStatus() {
    const status = el('status');
    if (!state.origin) {
      status.dataset.quality = 'off';
      status.textContent = 'Nocturne cannot run on this kind of page';
      return;
    }
    if (!state.settings.enabled || ((state.settings.sites || {})[state.origin] || {}).enabled === false) {
      status.dataset.quality = 'off';
      status.textContent = 'Off for this site';
      return;
    }

    const report = state.tabId ? await NX.browser.sendToTab(state.tabId, { type: MSG.GET_STATE }) : null;
    if (!report || report.tier == null) {
      status.dataset.quality = 'off';
      status.textContent = 'Reload the page to theme it';
      return;
    }
    const [quality, copy] = TIER_COPY[report.tier] || TIER_COPY[0];
    status.dataset.quality = quality;
    status.textContent = copy;
  }

  async function save(patch) {
    const next = { ...state.settings, ...patch };
    const reply = await NX.browser.send({ type: MSG.SET_SETTINGS, settings: next });
    state.settings = reply ? reply.settings : NX.settings.sanitise(next);
    render();
  }

  async function saveSite(patch) {
    if (!state.origin) return;
    const reply = await NX.browser.send({ type: MSG.SET_SITE, origin: state.origin, patch });
    if (reply && reply.settings) state.settings = reply.settings;
    render();
  }

  function wire() {
    el('global').addEventListener('change', (event) => save({ enabled: event.target.checked }));
    el('site').addEventListener('change', (event) =>
      saveSite({ enabled: event.target.checked ? undefined : false })
    );

    for (const key of ['brightness', 'contrast', 'saturation']) {
      const input = el(key);
      // Live preview while dragging, one write when released, so a drag does
      // not produce fifty storage writes and fifty re-themes.
      input.addEventListener('input', () => {
        el(`${key}-out`).textContent = input.value;
      });
      input.addEventListener('change', () => saveSite({ [key]: Number(input.value) }));
    }

    el('reset').addEventListener('click', async () => {
      if (!state.origin) return;
      const reply = await NX.browser.send({ type: MSG.RESET_SITE, origin: state.origin });
      if (reply && reply.settings) state.settings = reply.settings;
      render();
    });

    el('options').addEventListener('click', () => {
      api.runtime.openOptionsPage();
      window.close();
    });
  }

  async function init() {
    const [tab] = await api.tabs.query({ active: true, currentWindow: true });
    state.tabId = tab ? tab.id : null;
    state.origin = tab ? NX.settings.originOf(tab.url) : null;
    state.settings = await NX.browser.readSettings();
    wire();
    render();
  }

  init();
})();
